services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.31.0
    container_name: ${AZURITE_CONTAINER_NAME}
    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"
      - "${AZURITE_QUEUE_PORT:-10001}:10001"
      - "${AZURITE_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
